import SwiftUI
import SwiftData

struct AIRoutineSetupView: View {
    @ObservedObject var vm: OnboardingViewModel
    @Environment(\.modelContext) private var context
    @State private var showAIDisclosure = false
    @State private var pendingGenerate = false

    var body: some View {
        VStack(spacing: 0) {
            Spacer()

            if vm.isGeneratingRoutine {
                loadingState
            } else {
                offerState
            }

            Spacer()
        }
        .onAppear {
            FirebaseAnalyticsService.shared.log(.onboardingStepViewed(step: "ai_setup"))
        }
        .alert("AI-Generated Content", isPresented: $showAIDisclosure) {
            Button("Generate Routine") {
                Task { await vm.generateRoutine(context: context) }
            }
            Button("Cancel", role: .cancel) {}
        } message: {
            Text("Your cleaning routine will be generated by an AI model (Claude by Anthropic). The suggestions are based on your home type and may not perfectly suit your specific situation. You can edit any task after setup.")
        }
    }

    private var offerState: some View {
        VStack(spacing: 32) {
            VStack(spacing: 16) {
                ZStack {
                    Circle()
                        .fill(Color.accent.opacity(0.12))
                        .frame(width: 100, height: 100)
                    Image(systemName: "brain.head.profile")
                        .font(.system(size: 44))
                        .foregroundStyle(Color.accent)
                }

                VStack(spacing: 8) {
                    Text("Let AI build your routine")
                        .font(.title2.bold())
                        .multilineTextAlignment(.center)

                    Text("Based on your rooms and lifestyle, we'll create a personalized cleaning schedule in seconds.")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                        .multilineTextAlignment(.center)
                }
            }
            .padding(.horizontal, 32)

            VStack(spacing: 12) {
                aiFeaturePill(icon: "clock", text: "Done in under 60 seconds")
                aiFeaturePill(icon: "slider.horizontal.3", text: "Fully customizable after setup")
                aiFeaturePill(icon: "arrow.clockwise", text: "1 free generation per month")
            }
            .padding(.horizontal, 24)

            VStack(spacing: 12) {
                Button {
                    HapticService.shared.trigger(.medium)
                    showAIDisclosure = true
                } label: {
                    HStack {
                        Image(systemName: "sparkles")
                        Text("Generate My Routine")
                    }
                    .font(.headline)
                    .frame(maxWidth: .infinity)
                    .padding()
                    .background(Color.accent)
                    .foregroundStyle(.white)
                    .clipShape(RoundedRectangle(cornerRadius: 16))
                }
                .padding(.horizontal, 24)
                .accessibilityLabel("Generate my cleaning routine with AI")

                Button {
                    vm.advance()
                } label: {
                    Text("Skip — I'll set it up myself")
                        .font(.subheadline)
                        .foregroundStyle(.secondary)
                }
                .accessibilityLabel("Skip AI setup")
            }
            .padding(.bottom, 40)
        }
    }

    private var loadingState: some View {
        VStack(spacing: 24) {
            ZStack {
                Circle()
                    .stroke(Color.accent.opacity(0.2), lineWidth: 4)
                    .frame(width: 80, height: 80)
                Circle()
                    .trim(from: 0, to: 0.7)
                    .stroke(Color.accent, style: StrokeStyle(lineWidth: 4, lineCap: .round))
                    .frame(width: 80, height: 80)
                    .rotationEffect(.degrees(-90))
                    .rotationEffect(Angle(degrees: Date().timeIntervalSince1970 * 200))
                    .animation(.linear(duration: 1).repeatForever(autoreverses: false), value: vm.isGeneratingRoutine)

                Image(systemName: "brain.head.profile")
                    .font(.system(size: 28))
                    .foregroundStyle(Color.accent)
            }

            VStack(spacing: 8) {
                Text("Building your routine...")
                    .font(.headline)
                Text("Analyzing your rooms and preferences")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
            }

            VStack(alignment: .leading, spacing: 8) {
                loadingPill(text: "Calculating cleaning frequencies")
                loadingPill(text: "Estimating task durations")
                loadingPill(text: "Optimizing schedule")
            }
        }
        .padding(.horizontal, 32)
    }

    private func aiFeaturePill(icon: String, text: String) -> some View {
        HStack(spacing: 12) {
            Image(systemName: icon)
                .foregroundStyle(Color.accent)
                .frame(width: 20)
            Text(text)
                .font(.subheadline)
            Spacer()
        }
        .padding(.horizontal, 20)
        .padding(.vertical, 10)
        .background(Color(.secondarySystemBackground))
        .clipShape(RoundedRectangle(cornerRadius: 10))
    }

    private func loadingPill(text: String) -> some View {
        HStack(spacing: 8) {
            Image(systemName: "checkmark.circle.fill")
                .foregroundStyle(Color.gleamGreen)
                .font(.system(size: 14))
            Text(text)
                .font(.subheadline)
                .foregroundStyle(.secondary)
        }
    }
}
